version: "3.9"
services:
  db:
    image: postgres:11-alpine
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always
#    ports:
#      - '5432:5432'
  backend:
    build:
        context: .
    image: backend
    expose:
      - ${APP_PORT}
    env_file:
      - ./.env
    depends_on:
      - db
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn sampleApp.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/microservice/static
    ports:
      - 1300:80
    depends_on:
      - backend
      - db

volumes:
  postgres_data:
  static_volume: