version: "3.7"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        command:
          - /bin/sh
          - /app/scripts/entrypoint.sh
        volumes:
          - ./:/app
        env_file:
          - ./.env
    postgresql:
        image: postgres
        environment:
          - POSTGRES_PASSWORD=password
        ports:
          - "5432:5432"
