version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  backend:
    build:
        context: .
    container_name: bilim
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command:
      - /bin/sh
      - /code/start.sh
    volumes:
      # - '${PWD}/start.sh:/code/start.sh'
      # - './gunicorn:/code/socket'
      # - './media:/code/media'
      # - './static:/code/static'
      - '.:/code'
  proxy:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - './media:/code/media'
      - './static:/code/static'
    ports:
      - "80:80"
    depends_on:
      - backend
      - db

volumes:
  postgres_data: