version: '3.7'

services:
    web:
        build:
            context: .
        command:
          - /bin/sh
          - /app/scripts/entrypoint.sh
        volumes:
            - static_data:/vol/web
        depends_on:
         - db
        ports:
         - "8000:8000"

    proxy:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        volumes:
            - static_data:/vol/static
        ports:
            - "80:80"
        depends_on:
            - web
            - db
    db:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        environment:
            - POSTGRES_PASSWORD=devpass
        volumes:
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"

volumes:
    static_data:
