# Generated by Django 3.2 on 2021-10-10 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='yourMail@bilim.kz', max_length=254, unique=True, verbose_name='eMail')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Name Surname')),
                ('phone', models.CharField(help_text='77071113377', max_length=12, null=True, unique=True, verbose_name='Mobile phone')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date of registration')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin?')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, null=True, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_activation', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activation',
                'verbose_name_plural': 'Activation',
            },
        ),
    ]
